setwd("~/Desktop/coursera/Exploratory Data Analysis")
download.file(url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",
              destfile = "project1.zip",method="curl")
file <- unzip("project1.zip")
data <- read.csv(file,header=T,sep =';')
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
data <- subset(data,Date=="2007-02-01"|Date=="2007-02-02")
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 <- as.numeric(as.character(data$Sub_metering_3))
data$Time<-strptime(paste(data$Date,data$Time),format="%Y-%m-%d %H:%M:%S")
data$Voltage <- as.numeric(as.character(data$Voltage))
data$Global_reactive_power<- as.numeric(as.character(data$Global_reactive_power))
par(mfrow=c(2,2))
plot(data$Time,data$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l")
plot(data$Time,data$Voltage,xlab="datetime",ylab="Voltage",type="l")
plot(data$Time,data$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(data$Time,data$Sub_metering_2,col="red")
lines(data$Time,data$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),y.intersp=0.4,cex=0.4,bty="n")
plot(data$Time,data$Global_reactive_power,xlab="datetime",type="l")
dev.copy(png,"plot4.png",width=480,height=480)
dev.off()
